/**
 * Project-local skills as a synthetic Claude Agent SDK plugin (ADR-0024).
 *
 * The SDK loads skills via plugins — there is no first-class "extra
 * skill discovery directory" option. To make `<workDir>/.marvin/skills/`
 * discoverable to the agent, we treat `<workDir>/.marvin/` AS a plugin:
 * we ensure a minimal `.claude-plugin/plugin.json` exists, then pass
 * `{ type: 'local', path: workDir + '/.marvin' }` to the SDK's
 * `plugins` option. The SDK then walks `skills/` inside that plugin.
 *
 * Two non-obvious rules baked in:
 *
 * 1. **Project-local skills SHADOW user-global ones on name conflict.**
 *    The SDK's plugin loader registers skills in load order; we ensure
 *    the project plugin loads alongside the user-global registry, and
 *    a project skill named `playwright-golden-path` wins precedence
 *    over a user-global skill of the same name. This mirrors the
 *    precedence rule per-project MCP server overrides already follow.
 *
 * 2. **No skills/ directory → no plugin.** We do NOT generate the
 *    manifest if `<workDir>/.marvin/skills/` doesn't exist. An empty
 *    plugin produces SDK warnings ("plugin has no contributions"),
 *    which is noise for projects that haven't built a skill yet. The
 *    plugin appears the moment the user adds their first skill dir.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * If `<workDir>/.marvin/skills/<name>/SKILL.md` exists for at least one
 * skill, ensure `<workDir>/.marvin/.claude-plugin/plugin.json` exists,
 * and return the plugin-spec entry the SDK expects. Otherwise return
 * `null` — the caller filters those out before passing to `Options`.
 *
 * The manifest is idempotent: we only write if missing. We never
 * overwrite a manifest the user has customised.
 */
export function projectSkillsPluginConfig(
  workDir: string,
): { type: "local"; path: string } | null {
  const skillsDir = join(workDir, ".marvin", "skills");
  if (!hasAnySkill(skillsDir)) return null;

  const pluginRoot = join(workDir, ".marvin");
  const manifestDir = join(pluginRoot, ".claude-plugin");
  const manifestPath = join(manifestDir, "plugin.json");

  if (!existsSync(manifestPath)) {
    try {
      mkdirSync(manifestDir, { recursive: true });
      // Minimal manifest. The SDK only requires name/version/description.
      // Authoring metadata is omitted on purpose — projects with a
      // legitimate need for it can replace this file; we won't overwrite.
      writeFileSync(
        manifestPath,
        JSON.stringify(
          {
            name: "marvin-project-local",
            version: "0.1.0",
            description:
              "Project-local skills committed to <workDir>/.marvin/skills/. " +
              "Auto-generated by MARVIN per ADR-0024 — safe to edit, MARVIN " +
              "will not overwrite this file.",
          },
          null,
          2,
        ) + "\n",
        { encoding: "utf-8" },
      );
    } catch {
      // Plugin creation is best-effort. If the project dir is
      // read-only (rare but possible — CI cache, mounted volume),
      // we silently skip. The SDK keeps working with user-global
      // skills only, and the user sees no error.
      return null;
    }
  }

  return { type: "local", path: pluginRoot };
}

/**
 * Returns true when `<workDir>/.marvin/skills/` contains at least one
 * subdirectory holding a `SKILL.md`. This is the signal that the user
 * has actually built (or is in the process of building) project-local
 * skills.
 */
function hasAnySkill(skillsDir: string): boolean {
  let entries: string[];
  try {
    const st = statSync(skillsDir);
    if (!st.isDirectory()) return false;
    entries = readdirSync(skillsDir);
  } catch {
    return false;
  }
  for (const name of entries) {
    if (name.startsWith(".")) continue;
    const skillMd = join(skillsDir, name, "SKILL.md");
    try {
      const st = statSync(skillMd);
      if (st.isFile() && st.size > 0) return true;
    } catch {
      /* skip */
    }
  }
  return false;
}

/**
 * Enumerate the project-local skills (name + description from the
 * frontmatter). Used by `skill-catalog.ts` for the "build/edit"
 * recommendation surface so the suggestion engine can tell the user
 * what's already there before recommending more.
 *
 * Returns `[]` on any error — never throws.
 */
export function listProjectSkills(
  workDir: string,
): Array<{ name: string; description: string; path: string }> {
  const skillsDir = join(workDir, ".marvin", "skills");
  const out: Array<{ name: string; description: string; path: string }> = [];
  let entries: string[];
  try {
    const st = statSync(skillsDir);
    if (!st.isDirectory()) return out;
    entries = readdirSync(skillsDir);
  } catch {
    return out;
  }
  for (const name of entries) {
    if (name.startsWith(".")) continue;
    const skillMd = join(skillsDir, name, "SKILL.md");
    try {
      const text = readFileSync(skillMd, "utf-8");
      const fm = parseFrontmatter(text);
      out.push({
        name: fm.name ?? name,
        description: fm.description ?? "",
        path: skillMd,
      });
    } catch {
      /* skip unreadable */
    }
  }
  return out;
}

/**
 * Tiny YAML-frontmatter parser. We only care about top-level scalar
 * `name:` and `description:` keys; nested keys / arrays are not in the
 * SKILL.md schema. Returns an empty object when the file has no
 * frontmatter or the frontmatter is malformed.
 */
function parseFrontmatter(text: string): { name?: string; description?: string } {
  if (!text.startsWith("---\n")) return {};
  const end = text.indexOf("\n---", 4);
  if (end < 0) return {};
  const block = text.slice(4, end);
  const out: { name?: string; description?: string } = {};
  for (const line of block.split("\n")) {
    const m = line.match(/^(\w+)\s*:\s*(.*)$/);
    if (!m) continue;
    const key = m[1];
    const valRaw = m[2] ?? "";
    const val = valRaw.trim().replace(/^['"](.*)['"]$/, "$1");
    if (key === "name" || key === "description") {
      out[key] = val;
    }
  }
  return out;
}
